chore(deps): downgrade next-mdx-remote to v4.2.0 because of unhandled error `TypeError: _jsx is not a function`
see https://github.com/hashicorp/next-mdx-remote/issues/350